DROP TABLE IF EXISTS films_users;
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films_genres;
DROP TABLE IF EXISTS films;

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(100) not null,
    email    varchar(100) not null,
    login    varchar(100) not null,
    birthday date
);
CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null
);
CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) not null,
    description  varchar(500),
    release_date date,
    duration     int,
    mpa_id       int references mpa (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS films_users
(
    user_id int references users (id) ON DELETE CASCADE,
    film_id int references films (id) ON DELETE CASCADE,
    primary key (user_id, film_id)
);
CREATE TABLE IF NOT EXISTS friendships
(
    status   boolean DEFAULT FALSE,
    user1_id int references users (id) ON DELETE CASCADE,
    user2_id int references users (id) ON DELETE CASCADE,
    primary key (user1_id, user2_id)
);
CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  int references films (id) ON DELETE CASCADE,
    genre_id int references genres (id) ON DELETE CASCADE,
    primary key (genre_id, film_id)
);

